# Computer Vision

* Create dataset
* make folder train and test with cat and dog classes

In [17]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [18]:
import numpy as np

## Step2: Conver each class image into numpy tensor

In [3]:
train_data_gen = ImageDataGenerator(rescale=1.0/255)

In [4]:
train_data = train_data_gen.flow_from_directory(
    "./data/train/",
    target_size=(60,60),
    batch_size=1,
    class_mode='binary'
)

Found 8 images belonging to 2 classes.


In [5]:
print(train_data.class_indices)
print(train_data.class_mode)
print(train_data.classes)


{'cat': 0, 'dog': 1}
binary
[0 0 0 0 1 1 1 1]


# now create network

In [6]:
150*150*3

67500

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam, SGD

In [8]:
model = Sequential()
model.add(Flatten())
model.add(Dense(5000, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [9]:
model.compile(loss='binary_crossentropy',
             optimizer='adam',
             metrics=['acc'])

In [12]:
hist = model.fit(train_data,epochs=10)

Epoch 1/10
8/8 [==============================] - 2s 256ms/step - loss: 0.8405 - acc: 0.8750
Epoch 2/10
8/8 [==============================] - 2s 254ms/step - loss: 1.6543 - acc: 0.8750
Epoch 3/10
8/8 [==============================] - 2s 254ms/step - loss: 3.8066 - acc: 0.7500
Epoch 4/10
8/8 [==============================] - 2s 255ms/step - loss: 1.9130 - acc: 0.8750
Epoch 5/10
8/8 [==============================] - 2s 258ms/step - loss: 5.4964 - acc: 0.6250
Epoch 6/10
8/8 [==============================] - 2s 254ms/step - loss: 0.6539 - acc: 0.7500
Epoch 7/10
8/8 [==============================] - 2s 255ms/step - loss: 1.4812e-05 - acc: 1.0000
Epoch 8/10
8/8 [==============================] - 2s 268ms/step - loss: 0.4569 - acc: 0.8750
Epoch 9/10
8/8 [==============================] - 2s 270ms/step - loss: 0.2029 - acc: 0.8750
Epoch 10/10
8/8 [==============================] - 2s 252ms/step - loss: 2.4809e-09 - acc: 1.0000


# Testing

In [13]:
test_data = train_data_gen.flow_from_directory(
    "./data/test/",
    target_size=(60,60),
    batch_size=1,
    class_mode='binary'
)

Found 2 images belonging to 2 classes.


In [27]:
Y = model.predict(test_data)
Y

array([[1.4378525e-17],
       [9.8320687e-01]], dtype=float32)

In [20]:
np.where(Y>0, "Dog","Cat")

array([['Dog'],
       ['Dog']], dtype='<U3')

# predict on image 

In [22]:
from tensorflow.keras.preprocessing import image
import numpy as np
img = image.load_img("data/train/dog/2.jpeg", target_size=(60,60))
x= image.img_to_array(img)/255
x = x.reshape(1,-1)
model.predict(x)

array([[1.]], dtype=float32)

In [24]:
from tensorflow.keras.preprocessing import image
import numpy as np
img = image.load_img("data/train/cat/2.jpeg", target_size=(60,60))
x= image.img_to_array(img)/255
x = x.reshape(1,-1)
model.predict(x)>0

array([[ True]])

# Attendance

In [28]:
import re
import pandas as pd
x = """
Dr Najeed Ahmed Khan4:20 PM
Ok we will look at them in the future IA.
Syed Zaim Nazir4:23 PM
Thanks Dr Najeed
Nadir Ali4:23 PM
Thanks
Imran Ali4:52 PM
4210176950677
Syed Sajjad Ali Shah4:52 PM
1510120026221
Kenneth Fahad4:53 PM
3310541597331
Muhammad Fahad4:54 PM
4210117498405
Syed Umair Ahmed5:03 PM
4130485196673
Syed Mohammad Asad Asad5:04 PM
4240180561365
TARIQ JAMIL5:04 PM
42501-8229854-5
Agha Zohaib5:04 PM
4210168710111
Bilal Uddin5:04 PM
4220122191357
Rizwan Ali5:04 PM
4230174256393
MUSTAFA NADIMI5:04 PM
5440053241639
Zoya Ansari5:05 PM
4220186465696
syed daniyal5:05 PM
4250189782769
Nadir Ali5:06 PM
4130311530273
Madiha Obaid Obaid5:06 PM
42201 05920780
Syed Abbas Abbas5:11 PM
1234567890123
Syed Zaim Nazir5:11 PM
4220171026219
Syeda Zehra Nadeem5:39 PM
42301235878796
Syeda Zehra Nadeem5:49 PM
Correction: 4230123587896
Imran Ali5:50 PM
4210176950677
mcc-qjtf-rix
""".replace("-","")
cnic = pd.DataFrame(list(set(re.findall('\d{13}',x))),columns=['cnic'])
print(len(cnic))
cnic

18


cnic
0   1510120026221
1   4210176950677
2   1234567890123
3   4230174256393
4   4220186465696
5   3310541597331
6   4130311530273
7   4210117498405
8   4230123587879
9   4130485196673
10  4220171026219
11  4250189782769
12  4230123587896
13  4210168710111
14  4250182298545
15  4220122191357
16  4240180561365
17  5440053241639